CASE WHEN REG.NUM_CONSEC IS NULL AND NOT REG.COD_MONEDA_N IS NULL
           THEN 'TOTAL POR MONEDA ' || TO_CHAR(REG.COD_MONEDA_N)
           ELSE 
              CASE WHEN REG.NUM_CONSEC IS NULL AND REG.COD_MONEDA_N IS NULL
              THEN 'GRAN TOTAL'
              ELSE 
                TO_CHAR(REG.NUM_CONSEC)
              END  
         END;
/
SELECT CASE WHEN REG1.NUM_CONSEC IS NULL AND NOT REG1.COD_MONEDA_N IS NULL
           THEN 'TOTAL POR MONEDA ' || TO_CHAR(REG1.COD_MONEDA_N)
           ELSE 
              CASE WHEN REG1.NUM_CONSEC IS NULL AND REG1.COD_MONEDA_N IS NULL
              THEN 'GRAN TOTAL'
              ELSE 
                TO_CHAR(REG1.NUM_CONSEC)
              END  
         END AS NUM_CONSEC,
       REG1.FEC_MOVIM, REG1.COD_MONEDA_N, REG1.DES_MOVIM, REG1.res   --,
FROM (
    SELECT REG.NUM_CONSEC,
          REG.FEC_MOVIM, REG.COD_MONEDA_N, REG.DES_MOVIM, SUM(REG.MTO_MOVIM) as res   --,
    --    REG.NUM_FILGRUPO, REG.MTO_SALDO, REG.SAL_NETO--,
    --    SUM (REG.SAL_NETO) OVER (PARTITION BY REG.COD_MONEDA_n order by reg.num_consec) as mto_salacum,
    --    MTO_SALDO - SUM (REG.SAL_NETO) OVER (PARTITION BY REG.COD_MONEDA_n order by reg.num_consec) AS MTO_SALACUMREAL
    FROM (
        SELECT A.NUM_CONSEC, A.FEC_MOVIM, A.COD_MONEDA_N,
        A.DES_MOVIM, A.MTO_CREDITO, A.MTO_DEBITO,
        (CASE   WHEN  A.MTO_CREDITO > 0 THEN A.MTO_CREDITO ELSE - 1 * A.MTO_DEBITO END) as mto_movim,
        ROW_NUMBER()  OVER (PARTITION BY COD_MONEDA_N
                                  ORDER BY NUM_CONSEC) AS NUM_FILGRUPO,
        SALDO_MONEDA (A.COD_MONEDA_n) AS MTO_SALDO,
        (CASE WHEN A.MTO_DEBITO > 0 THEN -1 ELSE 1 END) * (A.MTO_CREDITO + A.MTO_DEBITO) AS SAL_NETO
        FROM TMPSALDOS A
        ORDER BY A.NUM_CONSEC
    ) REG
    GROUP BY GROUPING SETS((), (REG.COD_MONEDA_N), (REG.COD_MONEDA_N,REG.NUM_CONSEC, REG.FEC_MOVIM, REG.DES_MOVIM ))
    ORDER BY REG.COD_MONEDA_N
    ) REG1;
/