
  CREATE TABLE TMPSALDOS 
   (	"NUM_CONSEC" NUMBER(10,0), 
	"FEC_MOVIM" DATE, 
	"COD_MONEDA_N" NUMBER(3,0), 
	"DES_MOVIM" VARCHAR2(500 BYTE), 
	"MTO_CREDITO" NUMBER(18,2), 
	"MTO_DEBITO" NUMBER(18,2), 
	 CONSTRAINT "PK_TMPSALDOS" PRIMARY KEY ("NUM_CONSEC"))

